/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pratikum030625;

import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Toko extends javax.swing.JFrame {

    /**
     * Creates new form Toko
     */
    public Toko() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TOKO = new javax.swing.JLabel();
        labelBarang = new javax.swing.JLabel();
        labelHarga = new javax.swing.JLabel();
        labelJumlah = new javax.swing.JLabel();
        fieldHarga = new javax.swing.JTextField();
        cbNama = new javax.swing.JComboBox<>();
        fieldJmlBarang = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        labelPembelian = new javax.swing.JLabel();
        labelDiskon = new javax.swing.JLabel();
        fieldPembelian = new javax.swing.JTextField();
        fieldDiskon = new javax.swing.JTextField();
        labelBayar = new javax.swing.JLabel();
        fieldBayar = new javax.swing.JTextField();
        btnKembalian = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        labelPembayaran = new javax.swing.JLabel();
        fieldPembayaran = new javax.swing.JTextField();
        labelKembalian = new javax.swing.JLabel();
        fieldKembalian = new javax.swing.JTextField();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TOKO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TOKO.setText("TOKO EDCBA");

        labelBarang.setText("Nama Barang");

        labelHarga.setText("Harga");

        labelJumlah.setText("Jumlah Barang");

        fieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHargaActionPerformed(evt);
            }
        });

        cbNama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang", "Pena", "Pensil", "Buku", "Penghapus" }));
        cbNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNamaActionPerformed(evt);
            }
        });

        fieldJmlBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldJmlBarangActionPerformed(evt);
            }
        });

        btnTotal.setText("Hitung Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        labelPembelian.setText("Total Pembelian");

        labelDiskon.setText("Diskon");

        fieldPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPembelianActionPerformed(evt);
            }
        });

        labelBayar.setText("Total Bayar");

        fieldBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldBayarActionPerformed(evt);
            }
        });

        btnKembalian.setText("Hitung Kembalian");
        btnKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembalianActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        labelPembayaran.setText("Uang Pembayaran");

        fieldPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPembayaranActionPerformed(evt);
            }
        });

        labelKembalian.setText("Kembalian");

        fieldKembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKembalianActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPembelian)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelJumlah)
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(fieldDiskon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                            .addComponent(fieldBayar, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldPembelian, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldJmlBarang, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addComponent(labelBayar)
                                    .addComponent(labelDiskon)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelBarang)
                                        .addGap(37, 37, 37)
                                        .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelPembayaran)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(labelKembalian)
                                            .addGap(53, 53, 53)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldPembayaran)
                                                .addComponent(fieldKembalian)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(labelHarga)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(fieldHarga)
                                            .addComponent(btnKembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                        .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(TOKO)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TOKO)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBarang)
                    .addComponent(labelHarga)
                    .addComponent(fieldHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelJumlah)
                    .addComponent(fieldJmlBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTotal))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPembelian)
                    .addComponent(fieldPembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDiskon)
                    .addComponent(fieldDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBayar)
                    .addComponent(fieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPembayaran)
                    .addComponent(fieldPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKembalian))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKembalian)
                    .addComponent(fieldKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(557, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHargaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // Integer.parseInt() -> Mengubah String menjadi int
        int harga = Integer.parseInt(fieldHarga.getText());
        int jumlah = Integer.parseInt(fieldJmlBarang.getText());
        double diskon = 0;
        int tb = harga * jumlah;
        
        // Integer.toString() -> Mengubah int menjadi String
        fieldPembelian.setText(Integer.toString(tb));
        
        if(tb > 100000) {
            diskon = 0.1 * tb;
        }
        
        fieldDiskon.setText(Double.toString(diskon));
        
        double tbayar = tb - diskon;
        
        fieldBayar.setText(Double.toString(tbayar));
    }//GEN-LAST:event_btnTotalActionPerformed

    private void fieldJmlBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldJmlBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldJmlBarangActionPerformed

    private void fieldBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldBayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldBayarActionPerformed

    private void btnKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembalianActionPerformed
        double bayar = Double.parseDouble(fieldPembayaran.getText());
        double tbayar = Double.parseDouble(fieldBayar.getText());
        if(bayar < tbayar) {
            JOptionPane.showMessageDialog(this, "Uang anda kurang", "Pesan", JOptionPane.INFORMATION_MESSAGE);
        }
        double kembali = bayar - tbayar;
        fieldKembalian.setText(Double.toString(kembali));
    }//GEN-LAST:event_btnKembalianActionPerformed

    private void fieldPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPembayaranActionPerformed

    private void fieldKembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKembalianActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cbNama.setSelectedIndex(0);
        fieldHarga.setText("");
        fieldJmlBarang.setText("");
        fieldPembelian.setText("");
        fieldDiskon.setText("");
        fieldBayar.setText("");
        fieldPembayaran.setText("");
        fieldKembalian.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void cbNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNamaActionPerformed
        int brg = (int)cbNama.getSelectedIndex();
        switch(brg) {
            case 1: fieldHarga.setText("15000"); break;
            case 2: fieldHarga.setText("10000"); break;
            case 3: fieldHarga.setText("20000"); break;
            case 4: fieldHarga.setText("75000"); break;
        }
    }//GEN-LAST:event_cbNamaActionPerformed

    private void fieldPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPembelianActionPerformed
        
    }//GEN-LAST:event_fieldPembelianActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int pil = JOptionPane.showConfirmDialog(this, "Apakah yakin ingi keluar", "Peringantan", JOptionPane.YES_NO_OPTION);
        
        if(pil == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TOKO;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnKembalian;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> cbNama;
    private javax.swing.JTextField fieldBayar;
    private javax.swing.JTextField fieldDiskon;
    private javax.swing.JTextField fieldHarga;
    private javax.swing.JTextField fieldJmlBarang;
    private javax.swing.JTextField fieldKembalian;
    private javax.swing.JTextField fieldPembayaran;
    private javax.swing.JTextField fieldPembelian;
    private javax.swing.JLabel labelBarang;
    private javax.swing.JLabel labelBayar;
    private javax.swing.JLabel labelDiskon;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelJumlah;
    private javax.swing.JLabel labelKembalian;
    private javax.swing.JLabel labelPembayaran;
    private javax.swing.JLabel labelPembelian;
    // End of variables declaration//GEN-END:variables
}
